### PR TITLE
httpx==0.13.3 is required for pyrogram

### PR DESCRIPTION
**Pull request by Achu2234**

### CODE REVIEW

**Comment by AnjanaMadu** [comment]
Screenshot_20211010_102703_com android chrome
I think not required

**Comment by Achu2234** [comment]
ok but i using it in my bot

**Comment by Achu2234** [comment]
image

**Comment by AnjanaMadu** [comment]
> ok but i using it in my bot

Anyway as pyrogram requirements its not required

**Comment by Achu2234** [comment]
ok

**Pull request closed without merging**
