### PR TITLE
Will look better

### PR DESCRIPTION
**Pull request by Achu2234**
Added ping and uptime

### CODE REVIEW

**Comment by AnjanaMadu** [comment]
I think _human_time_duration is not defined

**Comment by Achu2234** [comment]
test it sir then mereg it

**Comment by Achu2234** [comment]
it will work

**Comment by Achu2234** [comment]
image

**Comment by AnjanaMadu** [comment]
> test it sir then mereg it

K. Ill test

**Comment by Achu2234** [comment]
k

**Comment by Achu2234** [comment]
image

I tested working well do u tested

**Comment by AnjanaMadu** [comment]
Not defined. Please recheck again!

**Comment by Achu2234** [comment]
ok

> Not defined. Please recheck again!

**Comment by Achu2234** [comment]
https://github.com/AnjanaMadu/VoiceChatStreamer/pull/10
check this

**Pull request closed without merging**
